version: '3.9'
services:

  postgres:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    image: postgres:11
    container_name: postgres
    hostname: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    restart: always
    networks:
      - backend

  liquibase-migrations:
    image: liquibase/liquibase:4.19.1
    container_name: liquibase
    depends_on:
      postgres:
        condition: service_healthy
    command:
      - --url=jdbc:postgresql://postgres:5432/postgres?user=postgres&password=password
      - --changeLogFile=master.xml
      - update
    volumes:
      - ../migration/src/main/resources/db/master.xml:/liquibase/master.xml
      - ../migration/src/main/resources/db/changelog:/liquibase/changelog

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: always

    #    environment:
    #      - RABBITMQ_DEFAULT_USER = user
    #      - RABBITMQ_DEFAULT_PASS = password
    ports:
      - 5672:5672
      - 15672:15672

  order-service:
    build: /order-service
    container_name: order-service
    ports:
      - "8083:8083"
    depends_on:
      liquibase-migrations:
        condition: service_completed_successfully
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/postgres
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASSWORD=password

  restaurant-service:
    build: /restaurant-service
    container_name: restaurant-service
    ports:
      - "8084:8084"
    depends_on:
      order-service:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/postgres
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASSWORD=password

  delivery-service:
    build: /delivery-service
    container_name: delivery-service
    ports:
      - "8081:8081"
    depends_on:
      order-service:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/postgres
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASSWORD=password

  notification-service:
    build: /notification-service
    container_name: notification-service
    ports:
      - "8082:8082"
    depends_on:
      order-service:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/postgres
      - SPRING_DATASOURCE_USER=postgres
      - SPRING_DATASOURCE_PASSWORD=password


networks:
  backend:
    name: backend
    external: false

volumes:
  postgres_data:
    external: false
    name: postgres_data
  migrations:
    external: false
    name: migrations_data
  rabbitmq_data:
  rabbitmq_logs:
#    external: false
#    name: rabbitmq_data
