package ru.liga.enums;

public enum StatusOrder {
    CUSTOMER_CREATED,
    CUSTOMER_PAID,
    CUSTOMER_CANCELLED,
    KITCHEN_ACCEPTED,
    KITCHEN_DENIED,
    KITCHEN_PREPARING,
    KITCHEN_REFUNDED,
    KITCHEN_FINISHED,
    DELIVERY_PENDING,
    DELIVERY_PICKING,
    DELIVERY_DENIED,
    DELIVERY_DELIVERING,
    DELIVERY_REFUNDED,
    DELIVERY_COMPLETE

}
