management:
  endpoints:
    web:
      exposure:
        include: "*" #<2>
        endpoint:
          health:
            show-details: ALWAYS

server:
  port: 8083

springdoc:
  swagger-ui:
    path: /swagger-ui


