server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
        - id: order-service
          uri: http://127.0.0.1:8083/orders
          predicates:
            - Path=/orders/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie

        - id: customer-service
          uri: http://127.0.0.1:8084/customers
          predicates:
            - Path=/customers/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie

        - id: restaurant-service
          uri: http://127.0.0.1:8081/restaurants
          predicates:
            - Path=/restaurants/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie

        - id: delivery-service
          uri: http://127.0.0.1:8080/couriers
          predicates:
            - Path=/couriers/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie

  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id: gateway
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8000/login/oauth2/code/{registrationId}"
            scope: openid,message.read
        provider:
          spring:
            issuer-uri: http://localhost:9000
